server:
  port: 8084

# spring.main.allow-circular-references=true

spring:
  application:
    name: SPRING-CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: "AUTHENTICATION-SERVICE"
          uri: lb://AUTHENTICATION-SERVICE # URL for the "authentication service" route
          predicates:
            - Path=/authentication-service/**

        - id: "SUPPORT-SERVICE"
          uri: lb://SUPPORT-SERVICE # URL for the "support service" route
          predicates:
            - Path=/support-service/**

        - id: "HORIZONS-SERVICE"
          uri: lb://HORIZONS-SERVICE # URL for the "horizons service" route
          predicates:
            - Path=/horizons-service/**

        - id: "STUDENTS-CONNECT-SERVICE"
          uri: lb://STUDENTS-CONNECT-SERVICE # URL for the "studnets connect service" route
          predicates:
            - Path=/students-connect-service/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route:
            RouteDefinitionLocator: INFO
